version: '3'

services:
  # Backend FastAPI service
  backend:
    build:
      context: ./ml
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./ml:/app
    environment:
      - PYTHONPATH=/app
    depends_on:
      - ollama

  # Frontend React service
  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  # Ollama service for embeddings and LLM
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    command: serve

volumes:
  ollama_data: